#!/usr/bin/env bash
# Publish data/planets.json as a GitHub Release asset and point data/RELEASE at it.
#
# The repo is code-only (planets.json is gitignored — a 6k build is ~90 MB); releases
# carry the data. Deploy builds fetch the asset via scripts/fetch_data.py using the tag
# committed in data/RELEASE.
#
# Usage:  scripts/release-data.sh [tag]        (default tag: data-YYYYMMDD-HHMM)
# After it succeeds: commit data/RELEASE and push — the deploy webhook does the rest.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

DATA=data/planets.json
[ -f "$DATA" ] || { echo "error: $DATA not found — run the pipeline first" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "error: gh not authenticated — run: gh auth login" >&2; exit 1; }

TAG="${1:-data-$(date +%Y%m%d-%H%M)}"
N=$(python3 -c "import json;d=json.load(open('$DATA'));print(len(d['planets']))")
SCHEMA=$(python3 -c "import json;print(json.load(open('$DATA'))['schema_version'])")
SIZE=$(python3 -c "import os;print(f'{os.path.getsize(\"$DATA\")/1e6:.1f}')")

gh release create "$TAG" "$DATA" \
  --title "Planet data $TAG" \
  --notes "planets.json: $N planets, schema v$SCHEMA, $SIZE MB. Generated by the pipeline; consumed by the deploy build via scripts/fetch_data.py."

echo "$TAG" > data/RELEASE
echo
echo "Release $TAG published ($N planets, $SIZE MB)."
echo "Next: git add data/RELEASE && git commit -m 'Data release $TAG' && push — the deploy rebuilds from it."
